# Generated by Django 5.2.3 on 2025-06-17 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_course_options_alter_material_options_and_more"),
        ("testing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "Ответ", "verbose_name_plural": "Ответы"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Вопрос", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "Тест", "verbose_name_plural": "Тесты"},
        ),
        migrations.AlterModelOptions(
            name="testattempt",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Попытка прохождения теста",
                "verbose_name_plural": "Попытки прохождения тестов",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если это правильный вариант ответа",
                verbose_name="Правильный ответ",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                help_text="Вопрос, к которому относится этот ответ",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="testing.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(
                help_text="Введите текст ответа (максимум 255 символов)",
                max_length=255,
                verbose_name="Текст ответа",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                help_text="Тест, к которому относится этот вопрос",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="testing.test",
                verbose_name="Тест",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(
                help_text="Введите текст вопроса", verbose_name="Текст вопроса"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="material",
            field=models.OneToOneField(
                help_text="Материал, к которому привязан этот тест",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="content.material",
                verbose_name="Учебный материал",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="title",
            field=models.CharField(
                help_text="Введите название теста (максимум 255 символов)",
                max_length=255,
                verbose_name="Название теста",
            ),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="passed",
            field=models.BooleanField(
                help_text="Успешно ли пройден тест", verbose_name="Пройден"
            ),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="score",
            field=models.IntegerField(
                help_text="Процент правильных ответов", verbose_name="Результат"
            ),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Время завершения теста",
                verbose_name="Дата и время прохождения",
            ),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="test",
            field=models.ForeignKey(
                help_text="Тест, который проходил пользователь",
                on_delete=django.db.models.deletion.CASCADE,
                to="testing.test",
                verbose_name="Тест",
            ),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, проходивший тест",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
