# Generated by Django 5.2.3 on 2025-06-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Преподаватель"),
                    ("student", "Студент"),
                    ("admin", "Администратор"),
                ],
                default="student",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
