# Generated by Django 5.2.3 on 2025-06-17 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "verbose_name": "Учебный материал",
                "verbose_name_plural": "Учебные материалы",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "verbose_name": "Раздел курса",
                "verbose_name_plural": "Разделы курса",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание курса (необязательно)",
                verbose_name="Описание курса",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                help_text="Преподаватель, создавший курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец курса",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Введите название курса (максимум 255 символов)",
                max_length=255,
                verbose_name="Название курса",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="content",
            field=models.TextField(
                help_text="Введите содержание учебного материала",
                verbose_name="Содержание материала",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="section",
            field=models.ForeignKey(
                help_text="Раздел, к которому относится этот материал",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="content.section",
                verbose_name="Раздел",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="title",
            field=models.CharField(
                help_text="Введите название учебного материала (максимум 255 символов)",
                max_length=255,
                verbose_name="Название материала",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                help_text="Курс, к которому относится этот раздел",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="content.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="title",
            field=models.CharField(
                help_text="Введите название раздела (максимум 255 символов)",
                max_length=255,
                verbose_name="Название раздела",
            ),
        ),
    ]
